services:
  - type: web
    name: esto-es-real
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_v6:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
